(function() {function m(a) {a={Options:a,Fields:[],FieldsByLevels:{},BuildQueryUpTo:function(b) {for(var a='',d=0,h=0;h<this.Fields.length;h++)if(g.IsLessOrEqualLevel(this.Fields[h].MinLevel,b.MinLevel)) {var f=this.Fields[h].GetValue();if(0<f.length||this.Fields[h]===b)a+=g.GetLevelsSigns(this.Fields[h].Levels),a+='[',a+=g.EscapeQuery(f),a+=']',d+=f.length;}else this.Fields[h].ClearValue();return 0<d?a:'';},IsTailField:function(a) {return null==g.Find(this.Fields,function(c) {return g.IsLessLevel(a.MaxLevel,
  c.MinLevel)&&''!==c.GetValue();});},RefreshForm:function(a,c) {for(var d=0;d<this.Fields.length;d++)this.Fields[d].ClearValue();for(d=0;d<c.length;d++)this.FieldsByLevels[c[d].level].AppendValue(c[d].type+' '+c[d].name);},Init:function() {for(var a=0;a<this.Options.fields.length;a++)this.Fields.push(n(this,this.Options.fields[a]));for(a=0;a<this.Fields.length;a++)for(Level in e.AddressLevels)g.IsLessOrEqualLevel(this.Fields[a].MinLevel,Level)&&g.IsLessOrEqualLevel(Level,this.Fields[a].MaxLevel)&&(this.FieldsByLevels[Level]=
  this.Fields[a]);},Dispose:function() {for(var a=0;a<this.Fields.length;a++)this.Fields[a].Dispose();}};a.Init();return a;}function n(a,b) {var c={Options:g.BuildFieldOptions(b,a.Options,'site/suggest/address'),AddressForm:a,Levels:b.levels,MinLevel:'',MaxLevel:'',EXT:{PrepareQuery:function(a) {return{query:this.AddressForm.BuildQueryUpTo(this),mode:'discrete',addresslim:this.Options.limit};},IsAllowedToSuggestOnFocus:function() {return this.AddressForm.IsTailField(this)&&this.Options.suggest_on_focus;},IsAllowedQuery:function(a,
  f) {var b=a.query&&0<a.query.length?!0:!1;b&&0===f.length&&(b=void 0===this.Options.suggest_on_empty?g.IsNumericLevel(this.MinLevel)&&this.MinLevel!==e.AddressLevels.Flat.name:this.Options.suggest_on_empty);return b;},OnChooseSuggestion:function(a) {var f=g.DecodeMachineAddress(a.machine);this.AddressForm.RefreshForm(this,f);this.Options.on_fetch&&(f=$.extend({query:a.sign},this.AddressForm.Options.api_options),f.output=f.output?f.output+'|json':'json',this.Options.user&&(f.user=this.Options.user),$.ajax({type:'GET',
  url:this.Options.ahunter_url+'site/fetch/address',data:f,cache:!1,context:this,success:function(f) {this.Options.on_fetch.call(this.Options.on_fetch_context,a,f.address);}}));}},GetValue:function() {return this.UserValue;},ClearValue:function() {this.ResetField('',!0);this.ClearSuggestions();},AppendValue:function(a) {var f=this.GetValue();f&&(f+=', ');this.ResetField(f+a,!0);},Init:function() {this.MinLevel=e.AddressLevels.Flat.name;this.MaxLevel=e.AddressLevels.Region.name;for(var a=0;a<this.Levels.length;a++)g.IsLessLevel(this.Levels[a],
  this.MinLevel)&&(this.MinLevel=this.Levels[a]),g.IsLessLevel(this.MaxLevel,this.Levels[a])&&(this.MaxLevel=this.Levels[a]);void 0===b.empty_msg&&this.MinLevel===e.AddressLevels.Flat.name&&(this.Options.empty_msg='');}};c.Init();var d=k(c.Options.id,c.Options.max_height,c.Options.z_index,c.Options.full_url,c.Options.empty_msg);return g.ExtendSuggester(d,c);}function p(a) {a={Options:g.BuildFieldOptions(a,{},'site/suggest/address'),EXT:{PrepareQuery:function(a) {return{query:a,addresslim:this.Options.limit};},
  IsAllowedToSuggestOnFocus:function() {return this.Options.suggest_on_focus;},OnChooseSuggestion:function(a) {if(this.Options.on_fetch) {var b=$.extend({query:a.sign},this.Options.api_options);b.output=b.output?b.output+'|json':'json';this.Options.user&&(b.user=this.Options.user);$.ajax({type:'GET',url:this.Options.ahunter_url+'site/fetch/address',data:b,cache:!1,context:this,success:function(b) {this.Options.on_fetch.call(this.Options.on_fetch_context,a,b.address);}});}}},Init:function() {}};a.Init();var b=
  k(a.Options.id,a.Options.max_height,a.Options.z_index,a.Options.full_url,a.Options.empty_msg);return g.ExtendSuggester(b,a);}function q(a) {a={Options:a,Fields:[],BuildQueryWithActiveField:function(a) {return{active:a.Tag,last_name:this.GetFieldValue('last_name'),first_name:this.GetFieldValue('first_name'),patronym:this.GetFieldValue('patronym')};},GetFieldValue:function(a) {var c=g.Find(this.Fields,function(c) {return c.Tag===a;});return null!=c?c.UserValue:'';},GetPerson:function() {for(var a={last_name:this.GetFieldValue('last_name'),
    first_name:this.GetFieldValue('first_name'),patronym:this.GetFieldValue('patronym'),full_name:''},c=0;c<this.Fields.length;c++)a.full_name.length&&this.Fields[c].UserValue.length&&(a.full_name+=' '),a.full_name+=this.Fields[c].UserValue;return a;},Init:function() {for(var a=0;a<this.Options.fields.length;a++)this.Fields.push(r(this,this.Options.fields[a]));},Dispose:function() {for(var a=0;a<this.Fields.length;a++)this.Fields[a].Dispose();}};a.Init();return a;}function r(a,b) {var c={Options:g.BuildFieldOptions(b,
  a.Options,'site/suggest/person'),PersonForm:a,Tag:b.tag,EXT:{PrepareQuery:function(a) {return $.extend(this.PersonForm.BuildQueryWithActiveField(this),{personlim:this.Options.limit});},IsAllowedToSuggestOnFocus:function() {return this.Options.suggest_on_focus;},IsAllowedQuery:function(a,f) {return 0<f.length;},OnChooseSuggestion:function(a) {this.Options.on_fetch&&this.Options.on_fetch.call(this.Options.on_fetch_context,a,this.PersonForm.GetPerson());}},Init:function() {}};c.Init();var d=k(c.Options.id,c.Options.max_height,
  c.Options.z_index,c.Options.full_url,c.Options.empty_msg);return g.ExtendSuggester(d,c);}function t(a) {a={Options:g.BuildFieldOptions(a,{},'site/suggest/person'),EXT:{PrepareQuery:function(a) {return{query:a,personlim:this.Options.limit};},IsAllowedToSuggestOnFocus:function() {return this.Options.suggest_on_focus;},OnChooseSuggestion:function(a) {this.Options.on_fetch&&this.Options.on_fetch.call(this.Options.on_fetch_context,a,{full_name:a.value});}},Init:function() {}};a.Init();var b=k(a.Options.id,a.Options.max_height,
  a.Options.z_index,a.Options.full_url,a.Options.empty_msg);return SolidSuggester=g.ExtendSuggester(b,a);}function k(a,b,c,d,h) {a={EXT:{PrepareQuery:function(a) {return{query:a};},IsAllowedToSuggestOnFocus:function() {return!0;},IsAllowedQuery:function(a,b) {return a.query&&0<a.query.length&&0<b.length;},OnFiledChange:function(a,b) {},OnChooseSuggestion:function(a) {}},jField:'string'==typeof a&&'#'!==a[0]&&'.'!==a[0]?$('#'+a):$(a),SuggestionsClass:'u-AhunterSuggestions',SuggestionClass:'u-AhunterSuggestion',
  SelectedSuggestionClass:'u-AhunterSelectedSuggestion',EmptySuggestionClass:'u-AhunterEmptySuggestion',jSuggestions:$('<div></div>'),Suggestions:[],SelectedIndex:-1,UserValue:'',ShownValue:'',IsHidden:!0,SplitText:function(a,b) {for(var c=/[\s\\\/,;.\-"'<>\[\]()*]/gi,d=0;d<a.length;) {var e=c.exec(a),e=null!==e?e.index:a.length;d<e&&b(d,e);d=e+1;}},FormatSuggestionValue:function(a) {var b=this.UserValue,c=[];this.SplitText(b,function(a,f) {c.push({word:b.substring(a,f).toLowerCase(),prefix:f===b.length});});
    var d='',e=0;this.SplitText(a,function(b,l) {d+=a.substring(e,b);var h=a.substring(b,l).toLowerCase(),k=g.Find(c,function(a,f) {return a.word===h||a.prefix&&a.word===h.substring(0,a.word.length);});k?(d+='<strong>'+a.substring(b,b+k.word.length)+'</strong>',d+=a.substring(b+k.word.length,l)):d+=a.substring(b,l);e=l;});d+=a.substring(e);d.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/&lt;(\/?strong)&gt;/g,'<$1>');return d;},ShowSuggestions:function() {var a=
  !0;this.UpdatePosition();this.jSuggestions.empty();this.Suggestions||(this.Suggestions=[]);if(0<this.Suggestions.length)for(var b=0;b<this.Suggestions.length;b++)$('<div>'+this.FormatSuggestionValue(this.Suggestions[b].value)+'</div>').appendTo(this.jSuggestions).addClass(this.SuggestionClass);else h?$('<div>'+h+'</div>').appendTo(this.jSuggestions).addClass(this.EmptySuggestionClass):a=!1;a?(this.jSuggestions.show(),this.IsHidden=!1,this.HighliteSuggestion(this.SelectedIndex)):this.ClearSuggestions();},
  HideSuggestions:function() {this.jSuggestions.hide();this.IsHidden=!0;},ClearSuggestions:function() {this.Suggestions=[];this.SelectedIndex=-1;this.jSuggestions.empty();this.HideSuggestions();},UpdatePosition:function() {var a=this.jField.offset();this.jSuggestions.css('position','absolute');this.jSuggestions.css('left',a.left);this.jSuggestions.css('top',a.top+this.jField.outerHeight());this.jSuggestions.css('width',this.jField.outerWidth());},NavigateSuggestions:function(a) {var b=!1;a.which===e.Keys.ESC?
    (b=!0,this.ResetField(this.UserValue),this.HideSuggestions()):a.which===e.Keys.DOWN&&0<this.Suggestions.length?(b=!0,this.IsHidden?(this.ShowSuggestions(),this.SelectSuggestion(this.SelectedIndex)):this.SelectSuggestion(this.SelectedIndex+1)):a.which===e.Keys.UP&&0<this.Suggestions.length?(b=!0,this.IsHidden?(this.ShowSuggestions(),this.SelectSuggestion(this.SelectedIndex)):this.SelectSuggestion(this.SelectedIndex-1)):a.which===e.Keys.ENTER&&!this.IsHidden&&0<=this.SelectedIndex?(b=!0,this.ResetField(this.ShownValue),
    this.EXT.OnChooseSuggestion.call(this,this.Suggestions[this.SelectedIndex]),this.ClearSuggestions()):a.which!==e.Keys.TAB||this.IsHidden||(0<=this.SelectedIndex?(this.ResetField(this.ShownValue),this.EXT.OnChooseSuggestion.call(this,this.Suggestions[this.SelectedIndex])):this.ResetField(this.UserValue),this.ClearSuggestions());return!b;},SelectSuggestion:function(a) {this.SelectedIndex=-1>a?this.Suggestions.length-1:a>=this.Suggestions.length?-1:a;-1!==this.SelectedIndex?(this.ShownValue=this.Suggestions[this.SelectedIndex].value,
  this.jField.val(this.ShownValue)):this.ResetField(this.UserValue);this.HighliteSuggestion(this.SelectedIndex);},ResetField:function(a,b) {this.UserValue===a||b||this.EXT.OnFiledChange.call(this,this.UserValue,a);this.ShownValue=this.UserValue=a;this.jField.val(a);},HighliteSuggestion:function(a) {this.jSuggestions.children().removeClass(this.SelectedSuggestionClass);-1!==a&&a<this.Suggestions.length&&(a=this.jSuggestions.children().get(a),$(a).addClass(this.SelectedSuggestionClass));},UpdateSuggestions:function(a) {var b=
  this.jField.val();if(this.ShownValue!==b||a) {var c=this;c.ResetField(b);c.SelectedIndex=-1;a=this.EXT.PrepareQuery.call(this,b);this.EXT.IsAllowedQuery.call(this,a,b)?(b=$.extend({output:'json',ahungest:e.Version},a),$.ajax({type:'GET',url:d,data:b,cache:!1,context:this,success:function(a) {c.Suggestions=a.suggestions;c.ShowSuggestions();}})):c.ClearSuggestions();}},Init:function() {var a=this;this.ResetField(this.jField.val(),!0);this.jSuggestions.addClass(this.SuggestionsClass);this.jSuggestions.css('max-height',
    b);this.jSuggestions.css('z-index',c);this.jSuggestions.hide();this.jSuggestions.appendTo(document.body);this.UpdatePosition();this.jField.attr('autocomplete','off');this.jSuggestions.on('mouseover'+e.EventsNamespace,'.'+this.SuggestionClass,function() {a.SelectedIndex=$(this).index();a.HighliteSuggestion(a.SelectedIndex);});this.jSuggestions.on('mouseout'+e.EventsNamespace,function() {a.SelectedIndex=-1;a.HighliteSuggestion(a.SelectedIndex);});this.jSuggestions.on('mousedown'+e.EventsNamespace,'.'+this.SuggestionClass,
    function(b) {if(1===b.which)return a.SelectedIndex=$(this).index(),a.SelectSuggestion(a.SelectedIndex),a.ResetField(a.ShownValue),a.EXT.OnChooseSuggestion.call(a,a.Suggestions[a.SelectedIndex]),a.ClearSuggestions(),b=a.EXT.IsAllowedToSuggestOnFocus,a.EXT.IsAllowedToSuggestOnFocus=function() {return!1;},a.jField.focus(),a.EXT.IsAllowedToSuggestOnFocus=b,!1;});this.jField.on('keydown'+e.EventsNamespace,function(b) {return a.NavigateSuggestions(b);});this.jField.on('keyup'+e.EventsNamespace,function() {a.UpdateSuggestions();});
  this.jField.on('input'+e.EventsNamespace,function() {a.UpdateSuggestions();});this.jField.on('change'+e.EventsNamespace,function() {a.UpdateSuggestions();});this.jField.on('blur'+e.EventsNamespace,function() {a.IsHidden||(a.ResetField(a.UserValue),a.ClearSuggestions());});this.jField.on('focus'+e.EventsNamespace,function() {a.EXT.IsAllowedToSuggestOnFocus.call(a)&&a.UpdateSuggestions(!0);});$(window).on('resize'+e.EventsNamespace,function() {a.UpdatePosition();});},Dispose:function() {this.jSuggestions.off(e.EventsNamespace);
    this.jField.off(e.EventsNamespace);$(window).off(e.EventsNamespace);this.jSuggestions.remove();}};a.Init();return a;}window.AhunterSuggest={Address:{Discrete:function(a) {var b={obj:null};$(document).ready(function() {b.obj=m(a);});this.Running.push(b);return b;},Solid:function(a) {var b={obj:null};$(document).ready(function() {b.obj=p(a);});this.Running.push(b);return b;},Running:[]},Person:{Discrete:function(a) {var b={obj:null};$(document).ready(function() {b.obj=q(a);});this.Running.push(b);},Solid:function(a) {var b=
  {obj:null};$(document).ready(function() {b.obj=t(a);});this.Running.push(b);},Running:[]},Dispose:function(a) {this.FindAndDispose(a,this.Address.Running);this.FindAndDispose(a,this.Person.Running);},FindAndDispose:function(a,b) {for(var c=-1,d=0;d<b.length;d++)b[d]===a&&(c=d);-1!==c&&(b[c].obj.Dispose(),b.splice(c,1));}};var e={Version:'1.2',EventsNamespace:'.ahungest',AddressLevels:{Region:{name:'Region',sign:'r',num:0},District:{name:'District',sign:'d',num:1},City:{name:'City',sign:'c',num:2},Place:{name:'Place',
    sign:'p',num:3},Site:{name:'Site',sign:'t',num:4},Street:{name:'Street',sign:'s',num:5},House:{name:'House',sign:'h',num:6},Building:{name:'Building',sign:'b',num:7},Structure:{name:'Structure',sign:'u',num:8},Flat:{name:'Flat',sign:'f',num:9}},Keys:{ESC:27,TAB:9,ENTER:13,UP:38,DOWN:40},DefaultOptions:{ahunter_url:'https://ahunter.ru/',empty_msg:'РќРµС‚ РїРѕРґС…РѕРґСЏС‰РµР№ РїРѕРґСЃРєР°Р·РєРё',limit:10,suggest_on_empty:!1,suggest_on_focus:!0,z_index:9999,max_height:500,id:void 0,on_fetch:void 0,on_fetch_context:void 0,
    user:void 0,api_options:void 0}},g={Find:function(a,b) {for(var c=null,d=0;d<a.length;d++)if(b(a[d])) {c=a[d];break;}return c;},IsLessLevel:function(a,b) {return e.AddressLevels[a].num<e.AddressLevels[b].num;},IsLessOrEqualLevel:function(a,b) {return e.AddressLevels[a].num<=e.AddressLevels[b].num;},IsNumericLevel:function(a) {return e.AddressLevels[a].num>=e.AddressLevels.House.num;},IsAddressLevel:function(a) {return a in e.AddressLevels;},FindAddressLevelBySign:function(a) {var b='';for(Level in e.AddressLevels)if(e.AddressLevels[Level].sign===
  a) {b=e.AddressLevels[Level].name;break;}return b;},GetLevelsSigns:function(a) {for(var b='',c=0;c<a.length;c++)b+=e.AddressLevels[a[c]].sign;return b;},EscapeQuery:function(a) {return a.replace(/([\\\[\]])/g,'\\$1');},DecodeMachineAddress:function(a) {for(var b=[],c=0,d='',h={name:'',type:'',level:e.AddressLevels.Region.name};c<a.length;) {if('\\'!==a[c]&&':'!==a[c]) {var f=g.FindAddressLevelBySign(a[c]);''===f?d+=a[c]:(h.name=d,b.push(h),d='',h={name:'',type:'',level:f},h.level=f);}else'\\'===a[c]?(c++,c<a.length&&
  (d+=a[c])):':'===a[c]&&(h.type=d,d='');c++;}0<d.length&&(h.name=d,b.push(h));return b;},ExtendSuggester:function(a,b) {var c=a.EXT;$.extend(a,b);a.EXT=$.extend(c,b.EXT);return a;},SelectDefined:function() {for(var a,b=0;b<arguments.length;b++)if(void 0!==arguments[b]) {a=arguments[b];break;}return a;},BuildFieldOptions:function(a,b,c) {var d={};for(Name in e.DefaultOptions)d[Name]=g.SelectDefined(a[Name],b[Name],e.DefaultOptions[Name]);'/'!==d.ahunter_url[d.ahunter_url.length-1]&&(d.ahunter_url+='/');d.full_url=
  d.ahunter_url+c;return d;}};})();
